#ifndef __HEALTHCHECKING_CONSTS_H
#define __HEALTHCHECKING_CONSTS_H
#define CTRL_MAP_SIZE 4
#define HC_MAIN_INTF_POSITION 3
#define REDIRECT_EGRESS 0
#define DEFAULT_TTL 64
#ifndef HC_MAX_PACKET_SIZE
#define HC_MAX_PACKET_SIZE 1474
#endif
#define GENERIC_STATS_INDEX 0
#define HC_FURTHER_PROCESSING -2
#define STATS_SIZE 1
#define NO_FLAGS 0
#define V6DADDR (1 << 0)
#define HC_SRC_MAC_POS 0
#define HC_DST_MAC_POS 1
#endif // of __HEALTHCHECKING_CONSTS_H
